<?php
/**
 * @file page.tpl.php
 * @see modules/system/page.tpl.php for drupal documentation of a page.tpl.php
 *
 * This is only a very basic example of how to use foundation classes.
 * Copy to your subtheme to start working with foundation grids as you need.
 *
 * class "row" is a special class dedicated to foundation framework.
 * Please @see http://foundation.zurb.com/docs/components/grid.html on how to use.
 * It's up to you to override this template and use grid classes as you like.
 *
 * Sidebars are handled by foundation grid classes, that may be configured
 * in theme settings if needed.
 *
 * The grid settings can be configured in _settings.scss file.
 *
 * Alternatively, you may wish to keep your html semantic with foundation grid mixins
 * to define rows and columns in your scss, rather than in html classes.
 */
?>

<?php // Display the grid if needed. You need to enable Grid viewer in theme settings. ?>
<?php if (isset($foundation_grid_viewer)) : ?>
  <?php print $foundation_grid_viewer ?>
<?php endif ?>

<?php //display topbar, if foundation_topbar plugin is enabled in theme settings. ?>
<?php if(isset($foundation_topbar)) :?>
  <?php print $foundation_topbar ?>
<?php endif ?>

<header>

  <?php // foundation rows ?>
  <div class="row header--row-1">
    <?php if(isset($page['header__row_1'])) print render($page['header__row_1']) ?>
  </div>
  <div class="row header--row-2">
    <?php if(isset($page['header__row_2'])) print render($page['header__row_2']) ?>
  </div>
  <div class="row header--row-3">
    <?php if(isset($page['header__row_3'])) print render($page['header__row_3']) ?>
  </div>
  <div class="row header--row-4">
    <?php if(isset($page['header__row_4'])) print render($page['header__row_4']) ?>
  </div>

</header>

<div class="row content-top--row-1">
  <?php if(isset($page['content_top__row_1'])) print render($page['content_top__row_1']) ?>
</div>
<div class="row content-top--row-2">
  <?php if(isset($page['content_top__row_2'])) print render($page['content_top__row_2']) ?>
</div>
<div class="row content-top--row-3">
  <?php if(isset($page['content_top__row_3'])) print render($page['content_top__row_3']) ?>
</div>
<div class="row content-top--row-4">
  <?php if(isset($page['content_top__row_4'])) print render($page['content_top__row_4']) ?>
</div>

<section class="content">
  <div class="row">

    <?php // sidebars and content classes contains foundation classes generated by dynamic_sidebars plugins ?>
    <?php if ($page['sidebar_first']): ?>
      <aside id="sidebar-first" class="<?php if (isset($sidebar_first_classes)) print $sidebar_first_classes ?>">
        <?php print render($page['sidebar_first']) ?>
      </aside>
    <?php endif ?>

    <?php // sidebars and content classes contains foundation classes generated by dynamic_sidebars plugins ?>
    <div id="content" class="<?php if (isset($content_classes)) print $content_classes ?>">

      <a id="main-content"></a>
      <?php print render($title_prefix) ?>
      <?php if ($title): ?><h1 class="title" id="page-title"><?php print $title; ?></h1><?php endif ?>
      <?php print render($title_suffix) ?>
      <?php if ($tabs): ?><div class="tabs"><?php print render($tabs); ?></div><?php endif ?>
      <?php print render($page['help']) ?>
      <?php if ($action_links): ?><ul class="action-links"><?php print render($action_links) ?></ul><?php endif ?>

      <div class="row">
        <?php print render($page['content']) ?>
      </div>

      <div class="row content-bottom--row-1">
        <?php if(isset($page['content_bottom__row_1'])) print render($page['content_bottom__row_1']) ?>
      </div>
      <div class="row content-bottom--row-2">
        <?php if(isset($page['content_bottom__row_2'])) print render($page['content_bottom__row_2']) ?>
      </div>
      <div class="row content-bottom--row-3">
        <?php if(isset($page['content_bottom__row_3'])) print render($page['content_bottom__row_3']) ?>
      </div>
      <div class="row content-bottom--row-4">
        <?php if(isset($page['content_bottom__row_4'])) print render($page['content_bottom__row_4']) ?>
      </div>

      <?php print $feed_icons ?>

    </div>

    <?php if ($page['sidebar_second']): ?>
      <aside id="sidebar-second" class="<?php if (isset($sidebar_second_classes)) print $sidebar_second_classes ?>">
        <?php print render($page['sidebar_second']) ?>
      </aside>
    <?php endif; ?>

  </div> <!-- /.row -->
</section>

<footer>
  <div class="row footer footer--row-1">
    <?php if(isset($page['footer__row_1'])) print render($page['footer__row_1']); ?>
  </div>
  <div class="row footer--row-2">
    <?php if(isset($page['footer__row_2'])) print render($page['footer__row_2']); ?>
  </div>
  <div class="row footer--row-3">
    <?php if(isset($page['footer__row_3'])) print render($page['footer__row_3']); ?>
  </div>
  <div class="row footer--row-4">
    <?php if(isset($page['footer__row_4'])) print render($page['footer__row_4']); ?>
  </div>
</footer>